import { appNavbarStyles, appShellStyles } from "../../styles/appTheme";

export const styles = {
  page: appShellStyles.page,
  navbar: { ...appNavbarStyles.shell, display: "grid", gridTemplateColumns: "1fr auto", alignItems: "center", gap: 16 },
  brand: { ...appNavbarStyles.brand, minWidth: 260 },
  brandTextWrap: appNavbarStyles.brandTextWrap,
  brandTitle: appNavbarStyles.brandTitle,
  brandSub: { ...appNavbarStyles.brandSub, fontSize: 13 },
  logoImg: appNavbarStyles.logoImg,
  rightWrap: { ...appNavbarStyles.rightWrap, flexWrap: "wrap" },
  profileBtn: { height: 46, cursor: "pointer", fontSize: 14, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 8px 20px rgba(0,0,0,0.08)", border: "none" },
  main: { width: "min(1180px, 92%)", margin: "0 auto", paddingBottom: 40 },
  pageHero: { position: "relative", padding: "24px 0 6px" },
  heroGlow: { position: "absolute", inset: 0, pointerEvents: "none" },
  alert: { padding: "14px 16px", borderRadius: 14, marginTop: 16, fontWeight: 600 },
  sectionHeader: { marginBottom: 16 },
  sectionTitle: { margin: 0, fontSize: 24, fontWeight: 800 },
  sectionSub: { marginTop: 6, fontSize: 14 },
  scoringLayout: { marginTop: 30, display: "grid", gridTemplateColumns: "320px 1fr", gap: 20, alignItems: "start" },
  sidebarCard: { borderRadius: 26, padding: 22, boxShadow: "0 14px 34px rgba(15,23,42,0.05)", position: "sticky", top: 100 },
  sideTitle: { margin: 0, fontSize: 20, fontWeight: 800 },
  criteriaNavBtn: { width: "100%", borderRadius: 18, padding: 14, cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
  criteriaBadge: { minWidth: 42, height: 34, padding: "0 10px", borderRadius: 999, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 800, whiteSpace: "nowrap" },
  searchCard: { borderRadius: 26, padding: 26, boxShadow: "0 14px 34px rgba(15,23,42,0.05)" },
  rangeRow: { display: "grid", gridTemplateColumns: "1fr 100px", gap: 12, alignItems: "center", marginTop: 6 },
  scoreInput: { width: "100%", padding: "13px 14px", borderRadius: 14, outline: "none", fontSize: 15, boxSizing: "border-box", fontWeight: 700 },
  searchBtn: { border: "none", color: "#fff", padding: "15px 18px", borderRadius: 16, cursor: "pointer", fontWeight: 700, fontSize: 15, boxShadow: "0 10px 22px rgba(47,150,180,0.25)" },
  label: { display: "block", marginBottom: 8, marginTop: 14, fontWeight: 700, fontSize: 14 },
  textarea: { width: "100%", minHeight: 110, padding: "13px 14px", borderRadius: 14, outline: "none", fontSize: 15, boxSizing: "border-box", resize: "vertical" },
  bottomActions: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap", marginTop: 22 },
  footer: { width: "min(1180px, 92%)", margin: "20px auto 0", padding: "18px 0 26px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap", fontSize: 14 },
  bandsHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" },
  bandCard: { width: "100%", borderRadius: 18, padding: 16, cursor: "pointer", textAlign: "left", boxSizing: "border-box" },
  bandIcon: { width: 46, height: 46, borderRadius: 14, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 800, flexShrink: 0 },
};
